version: '3.4'

services:
  microservicearchitecturedb:
    container_name: microservicearchitecturedb
    restart: always
    volumes:
       - ${WEBAPP_STORAGE_HOME}/site:/data/db
    ports:
       - "27017:27017"

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
       - "5672:5672"
       - "15672:15672"

  microservicearchitecturesqldb:
    container_name: microservicearchitecturesqldb
    ports:
        - "1433:1433"
    environment:
        SA_PASSWORD: "MA2019sqldb"
        ACCEPT_EULA: "Y"

  microservicearchitectureproducts:
    container_name: microservicearchitectureproducts
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ProductDatabaseSettings:ConnectionString=mongodb://microservicearchitecturedb:27017"
    depends_on:
        - microservicearchitecturedb
    ports:
      - "8000:80"
    volumes:
      - ${HOME}/ASP.NET/Https:/root/.aspnet/https/
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets

  microservicearchitecturesourcing:
    container_name: microservicearchitecturesourcing
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "SourcingDatabaseSettings:ConnectionString=mongodb://microservicearchitecturedb:27017"
      - "EventBus:HostName=rabbitmq"
    depends_on:
        - microservicearchitecturedb
        - rabbitmq
    ports:
      - "8001:80"
    volumes:
      - ${HOME}/ASP.NET/Https:/root/.aspnet/https/
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets

  microservicearchitectureorder:
    container_name: microservicearchitectureorder
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderConnection=Server=microservicearchitecturesqldb;Database=OrderDb;User Id=sa;Password=MA2019sqldb;"
      - "EventBus:HostName=rabbitmq"
    depends_on:
      - microservicearchitecturesqldb
      - rabbitmq
    ports:
      - "8002:80"
    volumes:
      - ${HOME}/ASP.NET/Https:/root/.aspnet/https/
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets

  microservicearchitectureapigateway:
    container_name: microservicearchitectureapigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - microservicearchitectureproducts
      - microservicearchitecturesourcing
      - microservicearchitectureorder
    ports:
      - "5000:80"
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      - ${HOME}/ASP.NET/Https:/root/.aspnet/https/